services:
  vidgo:
    image: jaceju68/video-miner:cuda-latest
    container_name: vidgo-app
    restart: unless-stopped
    runtime: nvidia
    network_mode: bridge
    env_file:
      - .env
    ports:
      - "${VIDGO_PORT}:8080"
      - "${VIDGO_MCP_PORT}:8787"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Make it able for container to access host by "host.docker.internal" 
    volumes:
      # Database files
      - ./data/videos.db:/app/database/videos.db
      # Media file folder
      - ./data/media:/app/media
      # User config folder
      - ./data/config:/app/config
      # Model root folder：For VidUnder、FunASR、GLM-ASR and More
      - ./data/models:/app/models
