# Generated by Django 5.2.1 on 2026-02-03 02:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名称', max_length=64, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='标签颜色（十六进制）', max_length=7)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=128, null=True)),
                ('srt_path', models.CharField(blank=True, max_length=128, null=True)),
                ('translated_srt_path', models.CharField(blank=True, help_text='翻译字幕文件路径', max_length=128, null=True)),
                ('video_length', models.CharField(blank=True, max_length=128, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='文件大小（字节）', null=True)),
                ('video_length_seconds', models.FloatField(blank=True, help_text='视频时长（秒），用于排序', null=True)),
                ('file_created_time', models.DateTimeField(blank=True, help_text='文件创建时间（从文件系统获取）', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chapters', models.JSONField(blank=True, default=list, help_text='视频章节信息，JSON格式存储', null=True)),
                ('notes', models.TextField(blank=True, help_text='视频笔记，Markdown格式，限制8000字符', max_length=8000, null=True)),
                ('video_source', models.CharField(blank=True, choices=[('bilibili', 'Bilibili'), ('youtube', 'YouTube'), ('ar_glass', 'AR Glass'), ('upload', 'Upload')], help_text='视频来源', max_length=20, null=True)),
                ('raw_lang', models.CharField(blank=True, choices=[('en', 'English'), ('zh', 'Chinese'), ('jp', 'Japanese')], help_text='视频原始语言', max_length=5, null=True)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后打开时间')),
                ('last_played_time', models.FloatField(default=0.0, help_text='记录视频上次播放到的秒数', verbose_name='上次播放时间（秒）')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='video.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='视频标签', related_name='videos', to='video.tag')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VideoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='生成的存储文件名', max_length=255)),
                ('original_name', models.CharField(help_text='用户原始文件名', max_length=255)),
                ('file_path', models.CharField(help_text='相对于MEDIA_ROOT的路径', max_length=500)),
                ('file_type', models.CharField(help_text="MIME类型，如'image/jpeg'", max_length=50)),
                ('file_size', models.IntegerField(help_text='文件大小（字节）')),
                ('context_type', models.CharField(choices=[('notes', 'Notes'), ('mindmap', 'Mindmap')], help_text='此附件的使用位置', max_length=20)),
                ('context_id', models.CharField(blank=True, help_text='在思维导图中使用时的节点ID', max_length=100)),
                ('alt_text', models.CharField(blank=True, help_text='可访问性的替代文本', max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='软删除时设为False')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='video.video')),
            ],
            options={
                'db_table': 'video_attachment',
                'ordering': ['-upload_time'],
                'indexes': [models.Index(fields=['video', 'context_type'], name='video_attac_video_i_d88444_idx'), models.Index(fields=['video', 'context_id'], name='video_attac_video_i_72e68a_idx')],
            },
        ),
    ]
