# Generated by Django 5.2.1 on 2026-03-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_url',
            field=models.CharField(blank=True, help_text='视频原始链接', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_source',
            field=models.CharField(blank=True, choices=[('bilibili', 'Bilibili'), ('youtube', 'YouTube'), ('ar_glass', 'AR Glass'), ('upload', 'Upload'), ('podcast', 'Podcast')], help_text='视频来源', max_length=20, null=True),
        ),
    ]
